# Sample GitLab Pipeline to deploy Enterprise Scale Landing Zone

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "This is a build test"

deploy:
  stage: deploy
  image:  mcr.microsoft.com/azure-cli:latest
  script:
    - echo $(ARM_CLIENT_ID)
    - az --version
    - az cloud set --name AzureUSGovernment
    - az login --service-principal -u ${ARM_CLIENT_ID} --password ${ARM_CLIENT_SECRET} --tenant ${ARM_TENANT_ID}
    - az account list

    # Management Group Deployment
    - az deployment tenant create --name "EntScale-Mgs-${LOCATION}" --location ${LOCATION} --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/mgmtGroups.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/mgmtGroups-parameters.json
        
    # Policy Deployment
    - az deployment mg create --name "EntScale-Policy-${LOCATION}" --location ${LOCATION} --management-group-id ${ENTERPRISE_SCALE_COMPANY_PREFIX} --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/policies.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/policies-parameters.json

    # Move Management Sub
    - az account management-group subscription add --name "${ENTERPRISE_SCALE_COMPANY_PREFIX}-management" --subscription ${MANAGMENT_SUB_ID}

    # Move Identity Sub
    - az account management-group subscription add --name "${ENTERPRISE_SCALE_COMPANY_PREFIX}-identity" --subscription ${IDENTITY_SUB_ID}

    # Move Online Subs
    #- Skip for now

    # Move Corp Subs
    #- Skip for now

    # Delay 20
    - sleep 20

    # Monitoring Deployment
    - az deployment mg create --name "EntScale-Monitoring-${LOCATION}" --location ${LOCATION} --management-group-id "${ENTERPRISE_SCALE_COMPANY_PREFIX}-management" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/logAnalytics.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/logAnalytics-parameters.json

    # Identity Deployment
    - az deployment mg create --name "EntScale-ID-${LOCATION}" --location ${LOCATION} --management-group-id "${ENTERPRISE_SCALE_COMPANY_PREFIX}-identity" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/identity.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/identity-parameters.json

    # Landing Zone Deployment
    - az deployment mg create --name "EntScale-LZ-${LOCATION}" --location ${LOCATION} --management-group-id "${ENTERPRISE_SCALE_COMPANY_PREFIX}-landingzones" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/lz.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/lz-parameters.json

    # Move Connectivity Sub
    - az account management-group subscription add --name "${ENTERPRISE_SCALE_COMPANY_PREFIX}-connectivity" --subscription ${CONNECTIVITY_SUB_ID}

    # Monitoring Solutions Deployment
    - az deployment sub create --name "EntScale-Solutions-${LOCATION}" --location ${LOCATION} --sub "${MANAGEMENT_SUB_ID}" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/logAnalyticsSolutions.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/logAnalyticsSolutions-parameters.json

    # Diagnostics and Security
    - az deployment mg create --name "EntScale-Solutions-${LOCATION}" --location ${LOCATION} --management-group-id "${ENTERPRISE_SCALE_COMPANY_PREFIX}" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/diagnosticsAndSecurity.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/diagnosticsAndSecurity-parameters.json

    # Connectivity Deployment
    - az deployment mg create --name "EntScale-conn-${LOCATION}" --location ${LOCATION} --management-group-id "${ENTERPRISE_SCALE_COMPANY_PREFIX}-connectivity" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/hubspoke-connectivity.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/hubspoke-connectivity-parameters.json    
