name: entlz-3-platform-management

env:
  entlzprefix: elz1
  environment: azureusgovernment
  location: usgovvirginia
  managementsubid: 07526f72-6689-42be-945f-bb6ad0214b71
  uniqueid: "2"

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

  push:
    branches:
      - dev
    paths:
      - 'templates/entlz/platform-management.bicep'
      - 'templates/entlz/modules/**'
      - '.github/workflows/entlz-3-platform-management.yml'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

          
        steps:
        - uses: actions/checkout@master        
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false
        
        - name: Deploy Management Components
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
              # Deploy Management Components to Management Subscription
                az deployment sub create \
                  --name "${{ env.entlzprefix }}-management-${{ env.location }}" \
                  --subscription "${{ env.managementsubid }}" \
                  --location "${{ env.location }}" \
                  --template-file "templates/entlz/platform-management.bicep" \
                  --parameters entlzprefix=${{ env.entlzprefix }} uniqueid=${{ env.uniqueid }}