name: entlz-3-platform-management

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  #push:
  #  branches:
  #    - master
  #  paths:
  #    - 'templates/entlz/platform-management.bicep'
  #    - '.github/workflows/entlz-4-platform-management.yml'
      
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
          entlzprefix: elz1
          environment: azureusgovernment
          location: usgovvirginia
          managementsubid: 07526f72-6689-42be-945f-bb6ad0214b71
          
        steps:
        - uses: actions/checkout@master        
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.JOBLEVINMAG_AZURE_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false
        
        - name: Deploy Management Components
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
              # Deploy Management Components to Management Subscription
                az deployment subscription create \
                  --name "entlz-management-${{ env.location }}" \
                  --subscription "${{ env.managementsubid }} \
                  --location ${{ env.location }} \
                  --template-file templates/entlz/platform-management.bicep \
                  --parameters entlzprefix=${{ env.entlzprefix }}