name: entlz-2-platform-subs

env:
  entlzprefix: entlz  
  environment: azureusgovernment
  location: usgovvirginia  
  managementsubid:
  identitysubid:
  connectivitysubid:
  securitysubid:
  subownergroup: azure-platform-owners
  offertype: MS-AZR-USGOV-0017P
  enracctname: b5f3295f-c2be-4afb-8880-5c0ce9be2db3

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master        
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false
        
        - name: Create Management Sub
          uses: azure/CLI@v1
          env:
            managementmg: "${{ env.entlzprefix }}-management"
            managementsubname: "${{ env.entlzprefix }}-management-001"
          with:
            azcliversion: 2.21.0
            inlineScript: |
              if [[ -z "${{ env.managementsubid }}" ]];
              then
                managementURI=$(az cloud show --query endpoints.resourceManager --output tsv)
                subownergroupid=$(az ad group list --display-name ${{ env.subownergroup }}  --query [].objectId -o tsv)

                # REST Call to Create Subscription
                az rest --method post \
                --url "${managementuri}providers/Microsoft.Billing/enrollmentAccounts/${{ env.enracctname }}/providers/Microsoft.Subscription/createSubscription?api-version=2019-10-01-preview" \
                --headers "{\"content-type\":\"application/json\"}" \
                --body "{\"displayName\": \"${{ env.managementsubname }}\", \"offerType\": \"${{ env.offertype }}\", \"owners\": [{\"objectId\": \"${subownergroupid}\"}]}"

                # Assign Default Tags to Subscription
                NOW=$(date +"%m/%d/%Y_%I:%M:%S_%p")
                subId=$(az account subscription list --query "[?displayName=='${{ env.managementsubname }}'].subscriptionId" --output tsv)
                az tag create --resource-id /subscriptions/$subId --tags createdOn="$NOW" programType="int" programEnv="prod" programName="${{ env.entlzprefix }}"
              else
                echo "Management subscription already exists...skipping"
              fi;

        - name: Create Identity Sub
          uses: azure/CLI@v1
          env:
            identitymg: "${{ env.entlzprefix }}-identity"
            identitysubname: "${{ env.entlzprefix }}-identity-001"
          with:
            azcliversion: 2.21.0
            inlineScript: |
              if [[ -z "${{ env.identitysubid }}" ]];
              then
                managementURI=$(az cloud show --query endpoints.resourceManager --output tsv)
                subownergroupid=$(az ad group list --display-name ${{ env.subownergroup }}  --query [].objectId -o tsv)

                # REST Call to Create Subscription
                az rest --method post \
                --url "${managementURI}providers/Microsoft.Billing/enrollmentAccounts/${{ env.enracctname }}/providers/Microsoft.Subscription/createSubscription?api-version=2019-10-01-preview" \
                --headers "{\"content-type\":\"application/json\"}" \
                --body "{\"displayName\": \"${{ env.identitysubname }}\", \"offerType\": \"${{ env.offertype }}\", \"owners\": [{\"objectId\": \"${subownergroupid}\"}]}"

                # Assign Default Tags to Subscription
                NOW=$(date +"%m/%d/%Y_%I:%M:%S_%p")
                subId=$(az account subscription list --query "[?displayName=='${{ env.identitysubname }}'].subscriptionId" --output tsv)
                az tag create --resource-id /subscriptions/$subId --tags createdOn="$NOW" programType="int" programEnv="prod" programName="${{ env.entlzprefix }}"
              else
                echo "Identity subscription already exists...skipping"
              fi;

        - name: Create Connectivity Sub
          uses: azure/CLI@v1
          env:
            connectivitymg: "${{ env.entlzprefix }}-connectivity"
            connectivitysubname: "${{ env.entlzprefix }}-connectivity-001"
          with:
            azcliversion: 2.21.0
            inlineScript: |
              if [[ -z "${{ env.connectivitysubid }}" ]];
              then
                managementURI=$(az cloud show --query endpoints.resourceManager --output tsv)
                subownergroupid=$(az ad group list --display-name ${{ env.subownergroup }}  --query [].objectId -o tsv)

                # REST Call to Create Subscription
                az rest --method post \
                --url "${managementURI}providers/Microsoft.Billing/enrollmentAccounts/${{ env.enracctname }}/providers/Microsoft.Subscription/createSubscription?api-version=2019-10-01-preview" \
                --headers "{\"content-type\":\"application/json\"}" \
                --body "{\"displayName\": \"${{ env.connectivitysubname }}\", \"offerType\": \"${{ env.offertype }}\", \"owners\": [{\"objectId\": \"${subownergroupid}\"}]}"

                 # Assign Default Tags to Subscription
                NOW=$(date +"%m/%d/%Y_%I:%M:%S_%p")
                subId=$(az account subscription list --query "[?displayName=='${{ env.connectivitysubname }}'].subscriptionId" --output tsv)
                az tag create --resource-id /subscriptions/$subId --tags createdOn="$NOW" programType="int" programEnv="prod" programName="${{ env.entlzprefix }}"
              else
                echo "Connectivity subscription already exists...skipping"
              fi;

        - name: Create Security Sub
          uses: azure/CLI@v1
          env:
            securitymg: "${{ env.entlzprefix }}-security"
            securitysubname: "${{ env.entlzprefix }}-security-001"
          with:
            azcliversion: 2.21.0
            inlineScript: |
              if [[ -z "${{ env.securitysubid }}" ]];
              then
                 managementURI=$(az cloud show --query endpoints.resourceManager --output tsv)
                 subownergroupid=$(az ad group list --display-name ${{ env.subownergroup }}  --query [].objectId -o tsv)

                # REST Call to Create Subscription
                az rest --method post \
                --url "${managementURI}providers/Microsoft.Billing/enrollmentAccounts/${{ env.enracctname }}/providers/Microsoft.Subscription/createSubscription?api-version=2019-10-01-preview" \
                --headers "{\"content-type\":\"application/json\"}" \
                --body "{\"displayName\": \"${{ env.securitysubname }}\", \"offerType\": \"${{ env.offertype }}\", \"owners\": [{\"objectId\": \"${subownergroupid}\"}]}"

                # Assign Default Tags to Subscription
                NOW=$(date +"%m/%d/%Y_%I:%M:%S_%p")
                subId=$(az account subscription list --query "[?displayName=='${{ env.securitysubname }}'].subscriptionId" --output tsv)
                az tag create --resource-id /subscriptions/$subId --tags createdOn="$NOW" programType="int" programEnv="prod" programName="${{ env.entlzprefix }}"
              else
                echo "Security subscription already exists...skipping"
              fi;

        - name: Log in to Azure Again
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false

        - name: Move Management Subscription to Management Group
          uses: azure/CLI@v1
          env:
            managementmg: "${{ env.entlzprefix }}-management"
            managementsubname: "${{ env.entlzprefix }}-management-001"
          with:
            azcliversion: 2.21.0
            inlineScript: |
              if [[ -z "${{ env.managementsubid }}" ]];
              then
                subId=$(az account subscription list --query "[?displayName=='${{ env.managementsubname }}'].subscriptionId" --output tsv)
                az account management-group subscription add --name "${{ env.managementmg }}" \
                  --subscription $subId
              else
                az account management-group subscription add --name "${{ env.managementmg }}" \
                  --subscription ${{ env.managementsubid }}
              fi;
        
        - name: Move Identity Subscription to Management Group
          uses: azure/CLI@v1
          env:
            identitymg: "${{ env.entlzprefix }}-identity"
            identitysubname: "${{ env.entlzprefix }}-identity-001"
          with:
            azcliversion: 2.21.0
            inlineScript: |
              if [[ -z "${{ env.identitysubid }}" ]];
              then
                subId=$(az account subscription list --query "[?displayName=='${{ env.identitysubname }}'].subscriptionId" --output tsv)
                az account management-group subscription add --name "${{ env.identitymg }}" \
                  --subscription $subId
              else
                az account management-group subscription add --name "${{ env.identitymg }}" \
                  --subscription ${{ env.identitysubid }}
              fi;

        - name: Move connectivity Subscription to Management Group
          uses: azure/CLI@v1
          env:
            connectivitymg: "${{ env.entlzprefix }}-connectivity"
            connectivitysubname: "${{ env.entlzprefix }}-connectivity-001"
          with:
            azcliversion: 2.21.0
            inlineScript: |
              if [[ -z "${{ env.connectivitysubid }}" ]];
              then
                subId=$(az account subscription list --query "[?displayName=='${{ env.connectivitysubname }}'].subscriptionId" --output tsv)
                az account management-group subscription add --name "${{ env.connectivitymg }}" \
                  --subscription $subId
              else
                az account management-group subscription add --name "${{ env.connectivitymg }}" \
                  --subscription ${{ env.connectivitysubid }}
              fi;

        - name: Move security Subscription to Management Group
          uses: azure/CLI@v1
          env:
            securitymg: "${{ env.entlzprefix }}-security"
            securitysubname: "${{ env.entlzprefix }}-security-001"
          with:
            azcliversion: 2.21.0
            inlineScript: |
              if [[ -z "${{ env.securitysubid }}" ]];
              then
                subId=$(az account subscription list --query "[?displayName=='${{ env.securitysubname }}'].subscriptionId" --output tsv)
                az account management-group subscription add --name "${{ env.securitymg }}" \
                  --subscription $subId
              else
                az account management-group subscription add --name "${{ env.securitymg }}" \
                  --subscription ${{ env.securitysubid }}
              fi;