name: entlz-6a-platform-connectivity-vnethubspoke
env:
  bastionsubnetprefix: 10.0.0.160/27
  connectivitysubid: b30166b8-dd1b-4fa2-9ad7-057614257b06
  entlzprefix: elz1
  environment: azureusgovernment
  fwmanagementsubnetprefix: 10.0.0.64/26
  fwsubnetprefix: 10.0.0.0/26
  fwtype: Standard
  gwsubnetprefix: 10.0.0.128/27
  gwtype: ExpressRoute
  hubmanagementsubnetprefix: 10.0.1.0/26
  hubvnetprefix: 10.0.0.0/23
  identitysubid: 787e871a-84ba-43be-86bf-86bd1e408a4a
  identitysubnetprefix: 10.0.4.0/26
  identityvnetprefix: 10.0.4.0/23
  location: usgovvirginia
  logaworkspaceid: /subscriptions/07526f72-6689-42be-945f-bb6ad0214b71/resourcegroups/elz1-management-usgovvirginia/providers/microsoft.operationalinsights/workspaces/elz1-loga-usgovvirginia2
  managementsubid: 07526f72-6689-42be-945f-bb6ad0214b71
  managementsubnetprefix: 10.0.2.0/26
  managementvnetprefix: 10.0.2.0/23
  securitysubid: ac95a806-c9d3-49e7-83ee-7f82e88c2bd3
  securitysubnetprefix: 10.0.6.0/26
  securityvnetprefix: 10.0.6.0/23
  

# Controls when the action will run. 
on:
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches:
      - dev
    paths:
      - 'templates/entlz/platform-connectivity-vnethubspoke**'
      - '.github/workflows/entlz-6a-platform-connectivity-vnethubspoke.yml'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
          
        steps:
         - uses: actions/checkout@v2
          with:
            ref: dev       
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false
        
        - name: Deploy Connectivity Components
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
              bastionsubnetprefix="${{ env.bastionsubnetprefix }}"
              connectivitysubid="${{ env.connectivitysubid }}"
              entlzprefix="${{ env.entlzprefix }}"
              environment="${{ env.environment }}"
              fwmanagementsubnetprefix="${{ env.fwmanagementsubnetprefix }}"
              fwsubnetprefix="${{ env.fwsubnetprefix }}"
              fwtype="${{ env.fwtype }}"
              gwsubnetprefix="${{ env.gwsubnetprefix }}"
              gwtype="${{ env.gwtype }}"
              hubmanagementsubnetprefix="${{ env.hubmanagementsubnetprefix}}"
              hubvnetprefix="${{ env.hubvnetprefix }}"
              identitysubid="${{ env.identitysubid }}"
              identitysubnetprefix="${{ env.identitysubnetprefix }}"
              identityvnetprefix="${{ env.identityvnetprefix }}"
              location="${{ env.location }}"
              managementsubid="${{ env.managementsubid }}"
              managementsubnetprefix="${{ env.managementsubnetprefix }}"
              managementvnetprefix="${{ env.managementvnetprefix }}"
              securitysubid="${{ env.securitysubid }}"
              securitysubnetprefix="${{ env.securitysubnetprefix }}"
              securityvnetprefix="${{ env.securityvnetprefix }}"
              logaworkspaceid="${{ env.logaworkspaceid }}"

              az deployment mg create \
                  --name "${entlzprefix}-connectivity-${location}" \
                  --management-group-id $entlzprefix \
                  --location $location \
                  --template-file "templates/entlz/platform-connectivity-vnethubspoke/platform-connectivity-vnethubspoke.bicep" \
                  --parameters \
                    bastionsubnetprefix="${bastionsubnetprefix}" \
                    connectivitysubid="${connectivitysubid}" \
                    entlzprefix="${entlzprefix}" \
                    environment="${environment}" \
                    fwmanagementsubnetprefix="${fwmanagementsubnetprefix}" \
                    fwsubnetprefix="${fwsubnetprefix}" \
                    fwtype="${fwtype}" \
                    gwsubnetprefix="${gwsubnetprefix}" \
                    gwtype="${gwtype}" \
                    hubmanagementsubnetprefix="${hubmanagementsubnetprefix}" \
                    hubvnetprefix="${hubvnetprefix}" \
                    identitysubid="${identitysubid}" \
                    identitysubnetprefix="${identitysubnetprefix}" \
                    identityvnetprefix="${identityvnetprefix}" \
                    location="${location}" \
                    managementsubid="${managementsubid}" \
                    managementsubnetprefix="${managementsubnetprefix}" \
                    managementvnetprefix="${managementvnetprefix}" \
                    securitysubid="${securitysubid}" \
                    securitysubnetprefix="${securitysubnetprefix}" \
                    securityvnetprefix="${securityvnetprefix}" \
                    logaworkspaceid="${logaworkspaceid}"