name: entlz-7a-platform-compliance-cmmc

env:
  entlzprefix: elz1
  environment: azureusgovernment
  location: usgovvirginia

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  #  push:
  #  branches:
  #    - master
  #  paths:
  #    - 'templates/entlz/platform-mgs.bicep'
  #    - '.github/workflows/entlz-1-platform-mgs.yml'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master        
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZGOV_CREDS }}
            environment: ${{ env.environment }}
            enable-AzPSSession: false