name: es-hubspoke-userlz-internal

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.USERLZ_AZURE_GOV_CREDENTIALS }}
            environment: ${{ secrets.USERLZ_AZURE_ENVIRONMENT }}
            enable-AzPSSession: false

        - name: Provision EA Subscription
          uses: azure/CLI@v1
          with:
            azcliversion: 2.21.0
            inlineScript: |
              resourceManagerURI=$(az cloud show --query 'endpoints.resourceManager' -o tsv)
              deploymentUser=$(az ad signed-in-user show --query objectId --output tsv)
              az rest --method post \
              --url "${resourceManagerURI}/providers/Microsoft.Billing/enrollmentAccounts/${{ USERLZ_ENROLLMENT_ACCOUNT_NAME }}/providers/Microsoft.Subscription/createSubscription?api-version=2019-10-01-preview" \
              --headers "{\"content-type\":\"application/json\"}" \
              --body "{\"displayName\": \"${{ USERLZ_SUBNAME }}\", \"offerType\": \"${{ USERLZ_OFFERTYPE }}\", \"owners\": [{\"objectId\": \"${deploymentUser}\"}]}"
#
#        - name: Add Subscription Tags
#          uses: azure/CLI@v1
#          with:
#            azcliversion: 2.21.0
#            inlineScript: |
#              NOW=$(date +"%m/%d/%Y_%I:%M:%S_%p")
#              USER=$(az ad signed-in-user show --query userPrincipalName --output tsv)
#              OWNER=$(az ad user show --id ${{ USERLZ_SUB_OWNER_OBJECT_ID }} )
#              az tag create --resource-id /subscriptions/${{ USERLZ_SUBNAME }} --tags createdOn="$NOW" createdBy="$USER" owner="$OWNER" 
#
#        - name: Move Subscription to Management Group
#          uses: azure/CLI@v1
#          with:
#            azcliversion: 2.21.0
#            inlineScript: |
#              az account management-group subscription add --name "${{ USERLZ_MANAGEMENT_GROUP }}" \
#              --subscription ${{ secrets.USERLZ_SUBNAME }}

#        - name: User Landing Zone Deployment
#          uses: azure/CLI@v1
#         with:
#            azcliversion: 2.21.0
#            inlineScript: |
#                az deployment sub create -f Templates/userlz/userlz-internal/templates/main.bicep -l ${{ secrets.USERLZ_LOCATION }} -p programName=${{ secrets.USERLZ_PROGRAM_NAME }} \
#                programType=${{ secrets.USERLZ_PROGRAM_TYPE }} programEnv=${{ secrets.USERLZ_PROGRAM_ENV }} vnetPrefix= ${{ secrets.USERLZ_VNET_PREFIX }} \
#                mgmtSubnetPrefix=${{ secrets.MGMT_SUBNET_PREFIX }} webSubnetPrefix= ${{ secrets.USERLZ_WEB_SUBNET_PREFIX  }} \
#                appSubnetPrefix=${{ secrets.APP_SUBNET_PREFIX }} dataSubnetPrefix=${{ secrets.DATA_SUBNET_PREFIX }} firewallIP=${{ secrets.FIREWALL_IP }}