name: es-hubspoke-deploy


# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LOCATION: usgovvirginia  
  ENTERPRISE_SCALE_COMPANY_PREFIX: jsb

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        
        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_GOV_ENTSCALE_CREDENTIALS }}
            environment: 'AzureUSGovernment'
            enable-AzPSSession: false

        - name: Azure CLI script
          uses: azure/CLI@v1
          with:
            azcliversion: 2.17.1
            inlineScript: |
                az account list

                # Management Group Deployment
                az deployment tenant create --name "EntScale-Mgs-${{ env.LOCATION }}" --location ${{ env.LOCATION }} --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/mgmtGroups.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/mgmtGroups-parameters.json

                # Policy Deployment
                az deployment mg create --name "EntScale-Policy-${{ env.LOCATION }}" --location ${{ env.LOCATION }} --management-group-id ${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }} --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/policies.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/policies-parameters.json

                # Move Management Sub
                az account management-group subscription add --name "${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }}-management" --subscription ${{ secrets.MANAGEMENT_SUB_ID }}

                # Move Identity Sub
                az account management-group subscription add --name "${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }}-identity" --subscription ${{ secrets.IDENTITY_SUB_ID }}

                # Move Online Subs
                #Skip for now

                # Move Corp Subs
                #Skip for now

                # Delay 20
                sleep 20

                # Monitoring Deployment
                az deployment mg create --name "EntScale-Monitoring-${{ env.LOCATION }}" --location ${{ env.LOCATION }} --management-group-id "${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }}-management" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/logAnalytics.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/logAnalytics-parameters.json

                # Identity Deployment
                az deployment mg create --name "EntScale-ID-${{ env.LOCATION }}" --location ${{ env.LOCATION }} --management-group-id "${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }}-identity" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/identity.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/identity-parameters.json

                # Landing Zone Deployment
                az deployment mg create --name "EntScale-LZ-${{ env.LOCATION }}" --location ${{ env.LOCATION }} --management-group-id "${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }}-landingzones" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/lz.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/lz-parameters.json

                # Move Connectivity Sub
                az account management-group subscription add --name "${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }}-connectivity" --subscription ${{ secrets.CONNECTIVITY_SUB_ID }}

                # Monitoring Solutions Deployment
                az deployment sub create --name "EntScale-Solutions-${{ env.LOCATION }}" --location ${{ env.LOCATION }} --sub "${{ secrets.MANAGEMENT_SUB_ID }}" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/logAnalyticsSolutions.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/logAnalyticsSolutions-parameters.json

                # Diagnostics and Security
                az deployment mg create --name "EntScale-Solutions-${{ env.LOCATION }}" --location ${{ env.LOCATION }} --management-group-id "${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }}" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/diagnosticsAndSecurity.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/diagnosticsAndSecurity-parameters.json

                # Connectivity Deployment
                az deployment mg create --name "EntScale-conn-${{ env.LOCATION }}" --location ${{ env.LOCATION }} --management-group-id "${{ env.ENTERPRISE_SCALE_COMPANY_PREFIX }}-connectivity" --template-file Templates/entscalelz/es-hubspoke-template/auxiliary/hubspoke-connectivity.json --parameters Templates/entscalelz/es-hubspoke-template/auxiliary/hubspoke-connectivity-parameters.json    
